- name: Installing Nginx 1.8.0
  yum: 
    name: nginx-1.8.0-1.el6.ngx
    state: latest
    enablerepo: nginx

- name: Apply Configuration
  template: src={{ nginx18.server_name }}.conf.j2 dest=/etc/nginx/conf.d/{{ nginx18.server_name }}.conf

- name: Launch Nginx
  service: name=nginx state=started enabled=yes
