- name: Installing Nginx 1.8.0
  yum: 
    name: nginx-1.8.0-1.el6.ngx
    state: latest
    enablerepo: nginx

- name: Apply Configuration
  template: src=example.com.conf.j2 dest=/etc/nginx/conf.d/{{ nginx18.server_name }}.conf
  notify:
    - Launch Nginx
