# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    Encoding.default_external = 'UTF-8'

    # box name
    config.vm.box = "vagrant_ansible"
    
    # box url
    config.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box"

    # port forwarding
    # config.vm.network "forwarded_port", guest: 80, host: 8080

    # using a specific IP
    config.vm.network "private_network", ip: "192.168.33.10"

    # sync folder settings
    config.vm.synced_folder "./", "/vagrant", :mount_options => ["dmode=755","fmode=644"]

    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end

    config.vm.provision "prepare", type: "shell" do |sh|
        sh.path = "prepare.sh"
    end

    config.vm.provision "provision1", type: "shell" do |sh|
        sh.path = "provision1.sh"
    end
end
