- hosts: web
  user: vagrant
  sudo: yes
  vars:
        mysql_root_pw: "3bcdj2caS2"
  tasks:
    - name: Install basepackage
      yum: name={{ item }} state=present
      with_items:
        - wget
        - ntp
        - vim
    - name: SELinux Disable
      command: setenforce 0
      ignore_errors: True
    - name: Edit selinux config
      command: sed -i -e "s/^SELINUX=enforing/SELINUX=disabled/g" /etc/selinux/config
    - name: stop iptabes
      service: name=iptables state=stopped
    - name: Install apache
      yum: name=httpd state=latest
      notify:
        - restart apache
    - name: Install php
      yum: name={{ item }} state=present
      with_items:
        - php
        - php-devel
        - php-mbstring
        - php-mysql
        - php-gd
      notify:
        - restart apache
    - name: Install mysql
      yum: name=mysql-server state=installed
      notify:
        - mysql setup
        - mysql set password
  handlers:
    - name: restart apache
      service: name=httpd state=restarted enabled=yes
    - name: mysql setup
      service: name=mysqld state=started enabled=yes
    - name: mysql set password
      command: mysqladmin -u root password "{{ mysql_root_pw }}"