- name: Installing Httpd 2.2.15
  yum:
    name: httpd
    state: latest

- name: Apply Configuration
  template: src=httpd.conf.j2 dest=/etc/httpd/conf/httpd.conf mode=0644 owner=root group=root

- name: Launch Httpd
  service: name=httpd state=started enabled=yes

