- name: Installing MySQL 5.5
  yum:
    name: "{{ item }}"
    state: latest
    enablerepo: mysql55-community
  with_items:
    - mysql-community-client
    - mysql-community-server

- name: Launch MySQL 5.5
  service: name=mysqld state=started enabled=yes
