- name: Installing MySQL 5.5
  yum: name={{ item }} state=latest enablerepo=mysql55-community
  with_items:
    - mysql-community-client
    - mysql-community-server
    # for Pyhton
    - MySQL-python

- name: Apply Configuration
  template: src=my.cnf.j2 dest=/etc/my.cnf

- name: Launch MySQL 5.5
  service: name=mysqld state=started enabled=yes

- name: Create Database
  mysql_db: name={{ item }} state=present encoding={{ mysql55.encode }}
  with_items: mysql55.db_name

- name: Copying Dump Data
  copy: src={{ item }}.sql.gz dest=/tmp
  with_items: mysql55.db_name

- name: Import Dump Data
  mysql_db: name={{ item }} state=import target=/tmp/{{ item }}.sql.gz
  with_items: mysql55.db_name
