#
# 開発環境用 playbook
#

# hosts ファイルのグループ(Windows: windows_host, Mac: development)
- hosts: "{{ provision_target }}"
  #
  # vagrant ユーザーが sudo でタスクを実施するための設定
  #
  user: vagrant
  sudo: yes
  #
  # タスクは roles を使用してモジュール化するのがベスト
  #
  roles:
    - common
#     - nginx_14
#     - mysql_55
#     - jdk_1851
#     - php_56
