- name: Installing PHP 5.6
  yum:
    name: "{{ item }}"
    state: latest
    enablerepo: "remi,remi-php56"
  with_items:
    - php
    - php-devel
    - php-mbstring
    - php-mcrypt
    - php-mysql
    - php-mysqlnd
    - php-opcache
    - php-pecl-xdebug
    - php-pecl-xhprof
    - php-phpunit-PHPUnit

- name: Apply Configuration
  template: src=php.ini.j2 dest=/etc/php.ini
