# ユーザーとグループ作成
- name: create Groups
  group: name={{ item.name }} state=present
  with_items: common.user

- name: add Users
  user: name={{ item.name }} group={{ item.group }} password= state=present
  with_items: common.user

- name: chmod Users home
  file: path=/home/{{ item.name }} mode={{ item.home_permission }}
  with_items: common.user
