#
# ミドルウェア設定用 playbook
#
- hosts: localhost
  user: vagrant
  sudo: yes
  roles:
    - httpd22
    - mysql56
    - php55

# exclude
#     - nginx18
#     - mysql55
#     - php53
#     - jdk18

# @FUTURE
#     - httpd24
#     - php56
#     - jdk17
#     - maven32
#     - maven33
