- name: Installing MySQL 5.6
  yum:
    name: "{{ item }}"
    state: latest
    enablerepo: mysql56-community
  with_items:
    - mysql-community-client
    - mysql-community-server

- name: Launch MySQL 5.6
  service: name=mysqld state=started enabled=yes
