- name: Installing PHP 5.5
  yum:
    name: "{{ item }}"
    state: latest
    enablerepo: "remi,remi-php55"
  with_items:
    - php
    - php-devel
    - php-mbstring
    - php-mysql

- name: Apply Configuration
  template: src=php.ini.j2 dest=/etc/php.ini
